version: "3.7"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5433:5432
    volumes:
      - "data:/var/lib/postgresql"
  sample:
    container_name: sample-be
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - postgres
    ports:
      - 3003:3002
volumes:
  data: